---
# tasks file for roles/docker


- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Start Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
